name: Build and Deploy Flutter Web to RefinedStone.github.io

on:
  push:
    branches:
      - main   # geonsaehelper 리포의 main 브랜치 푸시 시 실행

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout geonsaehelper repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href /geonsaehelper/

      - name: Checkout RefinedStone.github.io repo
        uses: actions/checkout@v3
        with:
          repository: RefinedStone/RefinedStone.github.io
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: site

      - name: Copy build to docs/geonsaehelper
        run: |
          rm -rf site/docs/geonsaehelper
          mkdir -p site/docs/geonsaehelper
          cp -r build/web/* site/docs/geonsaehelper/

      - name: Commit and Push to RefinedStone.github.io
        run: |
          cd site
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/geonsaehelper
          git commit -m "Deploy geonsaehelper from CI" || echo "No changes to commit"
          git push origin main
